name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Run Unit Tests
        run: go test ./...

      - name: Vet
        run: go vet ./...
